### PR TITLE
Remove fancy quotes

### PR DESCRIPTION
**Pull request by sorawee**
Fixes racket/racket#2796

### CODE REVIEW

**Comment by philippemeunier** [comment]
Since this change does not require any translation, please do it in the
other translation files too if necessary, not just the English one.
Thanks.

Cheers,

Philippe


sorawee wrote:

**Comment by sorawee** [comment]
@philippemeunier I did take a look at other translations, but either (1) they are already (unintentionally) fixed or (2) they don't use the same quote characters. German, French, and Bulgarian in particular use `„~s“` and `« ~s »`. So I thought that it's better to leave this to translators, in case that's really how they want it to be. But if you can confirm that these quote characters can be safely removed, I will do it.

**Comment by philippemeunier** [comment]
Honestly, apart from you I don't think anybody cares whether those quotes
are there or not, so go right ahead and then at least it will be consistent
across all translations :-)

Cheers,

Philippe


sorawee wrote:

**Comment by rfindler** [comment]
I was just coming to same the same thing as @philippemeunier ! The translators won't have any stake in this and we'll take a look and see if the changes seem reasonable.

**Comment by sorawee** [comment]
Fixed for other languages (German, French, and Bulgarian)

**Comment by rfindler** [comment]
Looks good to me, thanks!

**Pull request merged**
