### PR TITLE
initial Turkish translation

### PR DESCRIPTION
**Pull request by fatihpense**
I'm open to suggestions. Thanks.

### CODE REVIEW

**Comment by rfindler** [comment]
Thank you for this contribution! Have you found the translators mailing list?

**Comment by rfindler** [comment]
Also: do you know what the right entry is for this table?

https://github.com/racket/string-constants/blob/master/string-constants-lib/string-constants/string-constant.rkt#L38-L51

**Comment by rfindler** [comment]
I have pushed your commit to the `turkish` branch in the string-constants repo, along with adding Turkish to the list of languages. This will let you see your work in DrRacket. Let me know if you need advice on how to use the code on that branch in the context of the larger drracket git build.

**Comment by fatihpense** [comment]
Thanks! 

1- I found translators mailing list.
2- I think the entry for that table should be:
```
(turkish             #rx"^tr_"        #rx"^Turkish_")
```
3- Is it hacky "in a good way" to copy files from `turkish` branch to `C:\Program Files\Racket\share\pkgs` to see and test my translation?

**Comment by rfindler** [comment]
Okay, I've pushed that change (#2).

You can do that, but if you have a recent version of Racket (i.e. one from
the snapshot builds here: http://pre.racket-lang.org/installers/) then you
should instead run the command:

 raco pkg update --clone string-constants

this will create a string-constants directory and put a git repo in it.
Check out the turkish branch there and then edit away.

Let me know if you run into trouble.

Robby

**Comment by fatihpense** [comment]
Command line output:
```
Inferred package name from given `--clone' path
  package: string-constants
  given path: string-constants
Inferred package scope: installation
open-output-file: cannot open output file
  path: C:\Program Files\Racket-6.2.0.2\share\pkgs\_LOCKpkgs.rktd
  system error: Access is denied.; errno=5
  context...:
   C:\Program Files\Racket-6.2.0.2\collects\racket\private\kw-file.rkt:116:2: call-with-output-file*70
   C:\Program Files\Racket-6.2.0.2\collects\racket\file.rkt:357:0: call-with-file-lock40
   C:\Program Files\Racket-6.2.0.2\collects\pkg\main.rkt:323:16
   (submod C:\Program Files\Racket-6.2.0.2\collects\pkg\main.rkt main): [running body]
   C:\Program Files\Racket-6.2.0.2\collects\pkg\raco.rkt: [traversing imports]
   C:\Program Files\Racket-6.2.0.2\collects\raco\raco.rkt: [running body]
   C:\Program Files\Racket-6.2.0.2\collects\raco\main.rkt: [running body]
```

With administrator rights:
```
raco pkg update: package is not currently installed from a repository
```
I suppose these things would be much easier if I were using linux right now. 
Alternative I can think of: I can put my fork repo there manually. As long as I can send pull request like this, I think there is no problem?

One more question out of curiosity: When will translation merge to release? After some percent like %80 translated?

Thanks!

**Comment by rfindler** [comment]
Ah, sorry; this is the right command line:

    raco pkg update --clone string-constants https://github.com/racket/string-constants.git?path=string-constants-lib

After that, in the "string-constants" directory you should have a clone of the repo. Make your edits there and then push to a new remote you set up for making the pull request.

As for the 80% question, I don't have any specific number in mind. My ideal thing is that you'd spend time working on it to get all of the translated, join the mailing list and periodically update the string constants as they come in. Of course, if you can't make that kind of commitment, I'm happy to take whatever you have to give! I do realize the fee your getting isn't exactly, um, non-zero..... and we are all very happy for whatever effort you put in. 

Thank you.

**Comment by fatihpense** [comment]
Thank you! It is more fluent now. I hope I can make that commitment :) I'm having fun anyway.

**Pull request closed without merging**
