### PR TITLE
New constants about tools

### PR DESCRIPTION
**Pull request by alshopov**
Bump version

### CODE REVIEW

**Comment by alshopov** [comment]
Land before https://github.com/racket/drracket/pull/346

**Comment by rfindler** [comment]
I think that the `tool-tool-phase` string constant corresponds to an error in the tool that the developer should be fixing, not something that should show up to the actual user of DrRacket (or, put another way, there are many many more string constants that we would need to add if we wanted to have ones with the intended audience of that message). In contrast, the `tool-error-phase1` message corresponds to a situation that is more of a generic catchall "something went wrong" that plausibly the end user would see. (That said, I wouldn't mind removing the `tool-error-phase1` errors.)

... do you agree?

**Comment by alshopov** [comment]
I have no firm opinion on this one. Will you be OK if I just revert tool-tool-phase message to just a constant - as it was before? I will also update the string-constants package pull request.

**Comment by rfindler** [comment]
That sound simplest (and probably best) to me. Thank you!

**Comment by alshopov** [comment]
> That sound simplest...
Done. The corresponding PR https://github.com/racket/drracket/pull/346 has also been updated and both are ready to land

**Comment by alshopov** [comment]
Land before https://github.com/racket/string-constants/pull/44

**Pull request merged**
