### PR TITLE
revise some translate

### PR DESCRIPTION
**Pull request by MRNIU**
A little bit change

`使用简体中文作DrRacket界面语言` -> `使用简体中文作为DrRacket界面语言`
`无用的require`-> `无效的require`
`使用高亮突出`-> `使用高亮显示错误`
`"警告：定义视窗改变了。请单击“运行”`-> ` "警告：程序文件改变了。请单击“运行”。`

### CODE REVIEW

**Comment by rfindler** [comment]
The commit you suggest has many whitespace changes. I think the specific changes you write above are okay, but it is not okay to change all of the lines like that.

**Comment by bennn** [comment]
> "警告：定义视窗改变了。请单击“运行”-> "警告：程序文件改变了。请单击“运行”。

I don't know Chinese, but Google Translate says this is changing "the definition window" to "the program files". Is that true?

If that is true, that sounds like a bad change. At least in the English version of DrRacket, "the definitions window" is an important technical term:
http://docs.racket-lang.org/drracket/interface-essentials.html?q=definitions%20window#%28tech._definitions._window%29

**Comment by MRNIU** [comment]
@bennn 

Sorry, it's a free translation.

I think `for defining programs` in `Interface Essentials` means "edit source file (编辑源文件)".
In my opinion, `define` is used to define functions, not a whole program.

**Comment by rfindler** [comment]
@MRNIU thank you for your free offering. As you can see, we are passionate about getting every detail right, even though we cannot read the Chinese! You, no doubt, understand the context of the language better than we do, but we understand Racket and its history better. 

Anyway, if you have the time to engage with us to help us make the translation better, we would appreciate it.

Thank you for what you've provided already.

**Comment by stamourv** [comment]
FWIW, I read @MRNIU's comment as meaning "free translation" in the sense of "free vs literal translations". That is, conserving the meaning of the text, but not necessarily mapping terms one to one. IANATranslator, though.

My personal opinion is that technical terms, such as "definition window" are better served by a literal translation. But again, IANAT.

And of course, I will echo @rfindler in that we're very grateful for your help and contribution!

**Comment by MRNIU** [comment]
Sorry, the reply is so late.
I understand.Thanks for your reply.
Than this PR can be over?
Thank you for the help.

**Comment by rfindler** [comment]
Thank you for your input.

**Pull request closed without merging**
