### PR TITLE
Clarify that menu-keybindings relate to Emacs.

### PR DESCRIPTION
**Pull request by samth**
This is in response to a conversation on IRC where someone
asked for a way to do this and didn't know that this option
was relevant.

### CODE REVIEW

**Comment by stamourv** [comment]
I really like the idea.
The exact formulation confused me at first. How about `overrides` instead of `hides`?
(Though I guess the real confusion here is that, AFAICT,when people touch this option, they want to *enable* emacs keybindings (i.e. a positive action), but the option is about disabling menu keybindings (i.e., a negative action). Does that make any sense?)

**Comment by samth** [comment]
I like "overrides". I also agree about the confusion, but I I didn't come up a better solution. One issue is that it isn't "enable the emacs keybindings" since they're already enabled.

**Comment by stamourv** [comment]
Whatever we end up with is better than what we have currently.
Re already enabled: Sure, but not in an observable or useful way. For all practical purposes, they are disabled.

**Comment by harrisi** [comment]
One idea: have the option be "Enable CUA keybindings," as that's really what they are (or at least most of them - maybe "CUA-like" would be okay). However, that's probably a term that plenty of people aren't entirely aware of. Alternative: have the opposite behavior as currently exists; when the option is enabled, it uses Emacs keybindings, but when it's disabled it uses the "default" keybindings (with the option name being "Enable Emacs keybindings" or something.

One very confusing thing for me is that if the option is disabled currently, all the keybindings in the menu are not even visible. So the only way to know what it does or what the keybindings would be is to enable it. Not that it's a huge hassle, but it's a bit of an awkward workflow for that behavior.

**Pull request merged**
