### PR TITLE
Fixed the spelling of ‘sintaxis’ and some phrases in Spanish translation

### PR DESCRIPTION
**Pull request by rllullt**
Fixed the spelling of ‘sintaxis’ and improved the way some phrases where built, for example, ‘y envía el reporte de problemas por medio de la forma de web en esea página de WEB’ for ‘y envía el reporte de problemas por medio del formulario web en esa página’, that were found on the way.

### CODE REVIEW

**Comment by gus-massa** [comment]
I like the changes, and I'd merge this as is, but I'm worried about `checar` -> `chequear`. 

I strongly prefer `chequear` but [the first result in Google](http://udep.edu.pe/hoy/2013/cual-es-la-expresion-correcta-chequear-o-checar/) ([weird autotranlation](https://translate.google.com/translate?sl=auto&tl=en&u=http%3A%2F%2Fudep.edu.pe%2Fhoy%2F2013%2Fcual-es-la-expresion-correcta-chequear-o-checar%2F)) says that `checar` is more used in Mexico and `chequear` is more used elsewhere. (Hi from Argentina!)

Perhaps it's better to use another word like `revisar` or `controlar` instead. I'm still not sure where these strings are used, but I guess they must be similar to the string in [L78](https://github.com/racket/string-constants/pull/35/commits/4ab05dfebdf4686b11616f96e7c9acb9f3431828#diff-404ba31f1f3ce156033320a28d50ae30L78) thas says `Revisa la sintaxis`.

Can someone from Mexico give some insight about this? Do I send a question to the mailing list?

**Comment by gus-massa** [comment]
After taking a look, I think that [line 78](https://github.com/racket/string-constants/pull/35/commits/4ab05dfebdf4686b11616f96e7c9acb9f3431828#diff-404ba31f1f3ce156033320a28d50ae30L78) should be changed to `"Revisar la sintaxis"` (with an additional `r`), because the verb should be in imperative mode like the other buttons, for example `"Ejecutar"` or `"Interrumpir"`.

The initial part of lines [94-97](https://github.com/racket/string-constants/pull/35/commits/4ab05dfebdf4686b11616f96e7c9acb9f3431828#diff-404ba31f1f3ce156033320a28d50ae30L94) should use the exact same text. These are messages that appear at the bottom of the screen while Check-Syntax is running.

@rllullt can you make the changes. If not we can merge this and make the changes later. 

(It also would be nice to add Spanish somewhere in the title of the commit, so searching the history is easier.)

**Comment by rllullt** [comment]
I agree with what you say about the `"Revisar la sintaxis"`, I’m going to check that.
What do you think about the lines [94-97](https://github.com/racket/string-constants/pull/35/commits/4ab05dfebdf4686b11616f96e7c9acb9f3431828#diff-404ba31f1f3ce156033320a28d50ae30L94), should we probably use `"Revisión de sintaxis"` instead of `Checar` or `Chequear`? I say that because I read the English version of that strings, and it says `"Check Syntax: Initializing environment for user code"` so I think it could be a better translation given the noun and not the verb (in the lines [213-218](https://github.com/racket/string-constants/blob/master/string-constants-lib/string-constants/private/english-string-constants.rkt#L213))

**Comment by gus-massa** [comment]
I think it's better to use the exact same text, so it's more clear than the button somehow caused the text to appear. It's the convention in other languages packs, like Portuguese and German. (The problem with English is that sometimes the verb, the noun, and other related words are equal.)

**Comment by rllullt** [comment]
Ah ok now I understand. Yes, I think you are right. I’m going to put `"Revisar sintaxis"` in all of them.

**Comment by gus-massa** [comment]
I took longer than I expected. Thanks for all the work.

Merged in https://github.com/racket/string-constants/commit/716efdc921c3dc195e9d098138c0f50831ff9876 .

**Pull request closed without merging**
