### PR TITLE
Update save-in-drs-format format.

### PR DESCRIPTION
**Pull request by LeifAndersen**

### CODE REVIEW

**Comment by LeifAndersen** [comment]
I should note that this PR coincides with https://github.com/racket/gui/pull/93#issuecomment-356441512

**Comment by rfindler** [comment]
Sorry, I should have been more clear. The right thing to do is to NOT change the meaning of any existing string, but instead to add a new one (and you add it only to the language(s) you speak; no need to edit other files).

**Comment by LeifAndersen** [comment]
Ah, okay. I can do that.

As for your PS acknowledged, thanks.

**Comment by alshopov** [comment]
As a translator I may add - commenting out translated strings with no context is definitely not the right thing to do.
If `save-in-drs-format` will no longer be used in future (after you add the new string) you may add note that the string will be retired. Both changing the meaning and commenting out will make it hard on translators to keep the strings in sync.

**Comment by LeifAndersen** [comment]
@alshopov Woops, I got the first part of the instructions right, but missed "and put a short comment there telling us the English string has changed and needs to be re-translated". Thanks for pointing that out. :)

**Comment by LeifAndersen** [comment]
@rfindler Yes, they will keep getting asked that every time they save. It was like that before I started, and I kept it that way. Once the file gets reloaded, however, DrRacket will stop asking that because the file is now just plain text.

Long story short, every time you try to save a file with non-textual elements (and you have DrRacket set to warn you), you'll get asked by DrRacket if you want to convert the file.

**Comment by LeifAndersen** [comment]
Okay, pushed. I've also tested it on my machine and it seems to work and I'll go squash+merge these changes once the tests pass if it looks good to you.

**Pull request merged**
