### PR TITLE
Initial Finnish translation

### PR DESCRIPTION
**Pull request by reflektoin**
There's also two typo fixes made in english-string-constants.rkt.

Some translations contain the English word in parenthesis. All suggestions are welcome.

### CODE REVIEW

**Comment by rfindler** [comment]
This looks great to me, thank you! I know nothing of Finnish so am happy to merge or if you prefer to see if we get some Finnish-speaker feedback first, that's okay too.

**Comment by reflektoin** [comment]
Thank you for developing Racket! Yes, you can merge this. This translation was mentioned in few places, but there wasn't any feedback. 

Will this become available to users in DrRacket some time after it's been merged? Maybe that way there would be some feedback.

In case someone reads this and wants to improve some of the translations. I've added comment "FI&EN" to the end of the line of some translations which I'm unsure, and/or which contain mix of English and Finnish.

**Comment by rfindler** [comment]
Okay, I've merged it (sorry for the delay here). We can see if anyone comments over the next three months, leading up to the next release; they'll be able to either get the Finnish translation via a git build or via a snapshot build. Then after that, it'll be included in the next release and more will be able to see it.

**Comment by rfindler** [comment]
One thing I noticed about the translation is that the preference dialog becomes very wide. I think this is because of the circled translation (which appears four times) in the screenshot. Is there a way to make it use fewer characters?

Screenshot 2023-05-04 at 8 10 21 PM

**Comment by rfindler** [comment]
Also, the translation
```
(quasiquote-printing-style "Peruuntuva lainaus(Quasiquote)")
```

seems to be making the language dialog (Racket | Choose Language... in English) very wide. Probably good to shrink that one down somehow too.

**Pull request merged**
